# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4395bf66e88c267312afdb389cae4ec107b5b3a8da966dc2f162102573c9fe548cdb26d12bb6f86cd9b5c9c5bb6cb796eb643dbb199feb8f6f0ccca426d1730

test:
  secret_key_base: c1c95a4a68bf7d51bfd4db095e488f58c8ee15815f17bcbdc9a1a8956b96b31326780f604157fe2910490aebe7e2fd13aa7ec9f6c4446d8b57efab51f9c1ca79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
